name: Continous Integration
on:
  push:
    branches:
      - '*'
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Config Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
      - name: Runing the tests
        run: npm test
